ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - prisma
  - sharp
