# apps/core-svc/alembic/versions/20260203_add_iso42001_requirements_table.py
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# --- Alembic identifiers ---
revision = "6a2c9d4f1b70"
down_revision = "3f1a9c7d2e8b"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "iso42001",
        sa.Column("chapter", sa.Text(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("article", sa.Text(), primary_key=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("coverage", sa.Text(), nullable=True),
        sa.Column("eu_ai_act_articles", sa.Text(), nullable=True),
        sa.Column("eu_ai_act_alignment_note", sa.Text(), nullable=True),
    )

    rows = [
        {
            "chapter": "4",
            "section": "4.1",
            "article": "Context of the organisation",
            "content": "Determine internal and external issues relevant to AI objectives and outcomes",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No equivalent in EU AI Act",
        },
        {
            "chapter": "4",
            "section": "4.2",
            "article": "Stakeholders",
            "content": "Identify interested parties and their AI-related expectations",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "EU AI Act does not require stakeholder analysis",
        },
        {
            "chapter": "4",
            "section": "4.3",
            "article": "Scope of AIMS",
            "content": "Define and document scope of the AI Management System",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No scoping obligation in EU AI Act",
        },
        {
            "chapter": "4",
            "section": "4.4",
            "article": "AIMS establishment",
            "content": "Establish, implement, maintain, and improve an AI Management System",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "EU AI Act does not mandate management systems",
        },
        {
            "chapter": "5",
            "section": "5.1",
            "article": "Leadership & commitment",
            "content": "Top management must demonstrate leadership and accountability for AI governance",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "EU AI Act assigns liability, not leadership duties",
        },
        {
            "chapter": "5",
            "section": "5.2",
            "article": "AI policy",
            "content": "Establish and maintain an AI policy aligned with organisational goals",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No AI policy requirement in EU AI Act",
        },
        {
            "chapter": "5",
            "section": "5.3",
            "article": "Roles & responsibilities",
            "content": "Assign AI governance roles, authorities, and responsibilities",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 16, 26",
            "eu_ai_act_alignment_note": "EU AI Act implies roles but not governance structure",
        },
        {
            "chapter": "6",
            "section": "6.1",
            "article": "Risk & opportunity planning",
            "content": "Identify and address AI risks and opportunities",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 9",
            "eu_ai_act_alignment_note": "EU AI Act requires risk mgmt for high-risk AI",
        },
        {
            "chapter": "6",
            "section": "6.2",
            "article": "AI objectives",
            "content": "Define measurable AI objectives and plans to achieve them",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No objective-setting requirement",
        },
        {
            "chapter": "7",
            "section": "7.1",
            "article": "Resources",
            "content": "Provide resources necessary for AI governance",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "Not required by EU AI Act",
        },
        {
            "chapter": "7",
            "section": "7.2",
            "article": "Competence",
            "content": "Ensure personnel involved in AI are competent",
            "link": "ISO overview",
            "coverage": "Partial",
            "eu_ai_act_articles": "Art. 14(4), 29",
            "eu_ai_act_alignment_note": "EU AI Act limits this to oversight contexts",
        },
        {
            "chapter": "7",
            "section": "7.3",
            "article": "Awareness",
            "content": "Ensure awareness of AI risks, policies, and responsibilities",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No organisation-wide awareness duty",
        },
        {
            "chapter": "7",
            "section": "7.4",
            "article": "Communication",
            "content": "Establish internal and external AI communication processes",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "EU AI Act focuses on external transparency only",
        },
        {
            "chapter": "7",
            "section": "7.5",
            "article": "Documented information",
            "content": "Control AI-related documentation",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "EU AI Act requires docs, not doc control",
        },
        {
            "chapter": "8",
            "section": "8.1",
            "article": "Operational planning",
            "content": "Plan and control AI lifecycle processes",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 9",
            "eu_ai_act_alignment_note": "EU AI Act covers lifecycle for high-risk AI",
        },
        {
            "chapter": "8",
            "section": "8.2",
            "article": "Data governance",
            "content": "Ensure quality, relevance, and bias controls in data",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 10",
            "eu_ai_act_alignment_note": "Substantively identical",
        },
        {
            "chapter": "8",
            "section": "8.3",
            "article": "AI system design & development",
            "content": "Govern design and development of AI systems",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 11",
            "eu_ai_act_alignment_note": "EU AI Act focuses on documentation outcome",
        },
        {
            "chapter": "8",
            "section": "8.4",
            "article": "Intended purpose",
            "content": "Define and control intended use of AI systems",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 5, 9, 13",
            "eu_ai_act_alignment_note": "Embedded throughout EU AI Act",
        },
        {
            "chapter": "8",
            "section": "8.5",
            "article": "Transparency",
            "content": "Ensure appropriate AI transparency",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 13",
            "eu_ai_act_alignment_note": "Equivalent for high-risk AI",
        },
        {
            "chapter": "8",
            "section": "8.6",
            "article": "Human oversight",
            "content": "Implement human oversight measures",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 14",
            "eu_ai_act_alignment_note": "Equivalent",
        },
        {
            "chapter": "8",
            "section": "8.7",
            "article": "Accuracy & robustness",
            "content": "Ensure accuracy, robustness, reliability",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 15",
            "eu_ai_act_alignment_note": "Equivalent",
        },
        {
            "chapter": "8",
            "section": "8.8",
            "article": "Cybersecurity",
            "content": "Protect AI systems from attacks and misuse",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 15",
            "eu_ai_act_alignment_note": "Equivalent",
        },
        {
            "chapter": "8",
            "section": "8.9",
            "article": "Supplier & third parties",
            "content": "Manage AI-related supplier risks",
            "link": "ISO overview",
            "coverage": "Partial",
            "eu_ai_act_articles": "Art. 25, 28",
            "eu_ai_act_alignment_note": "EU AI Act defines roles, not governance",
        },
        {
            "chapter": "8",
            "section": "8.10",
            "article": "Monitoring",
            "content": "Monitor AI performance and behaviour",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 61",
            "eu_ai_act_alignment_note": "Equivalent",
        },
        {
            "chapter": "8",
            "section": "8.11",
            "article": "Incident handling",
            "content": "Detect, investigate, and respond to AI incidents",
            "link": "ISO overview",
            "coverage": "Shared",
            "eu_ai_act_articles": "Art. 62",
            "eu_ai_act_alignment_note": "EU AI Act focuses on serious incidents",
        },
        {
            "chapter": "9",
            "section": "9.1",
            "article": "Measurement & evaluation",
            "content": "Measure AI governance effectiveness",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No evaluation obligation",
        },
        {
            "chapter": "9",
            "section": "9.2",
            "article": "Internal audit",
            "content": "Conduct internal audits of AIMS",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No audit requirement",
        },
        {
            "chapter": "9",
            "section": "9.3",
            "article": "Management review",
            "content": "Top management reviews AIMS performance",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "No governance review obligation",
        },
        {
            "chapter": "10",
            "section": "10.1",
            "article": "Nonconformity & corrective action",
            "content": "Address AI governance failures systematically",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "EU AI Act requires fixes, not CAPA systems",
        },
        {
            "chapter": "10",
            "section": "10.2",
            "article": "Continual improvement",
            "content": "Continually improve AI governance",
            "link": "ISO overview",
            "coverage": "ISO-only",
            "eu_ai_act_articles": "N/A",
            "eu_ai_act_alignment_note": "Compliance law, not improvement framework",
        },
    ]

    iso_table = sa.table(
        "iso42001",
        sa.column("chapter", sa.Text()),
        sa.column("section", sa.Text()),
        sa.column("article", sa.Text()),
        sa.column("content", sa.Text()),
        sa.column("link", sa.Text()),
        sa.column("coverage", sa.Text()),
        sa.column("eu_ai_act_articles", sa.Text()),
        sa.column("eu_ai_act_alignment_note", sa.Text()),
    )
    op.bulk_insert(iso_table, rows)


def downgrade():
    op.drop_table("iso42001")
