"""scorecard kpi schema

Revision ID: 8d31d8f511e3
Revises: 
Create Date: 2025-10-16 18:16:04.145889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d31d8f511e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pillars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pillars_key'), 'pillars', ['key'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('target_threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pillar_id', sa.String(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('min_ideal', sa.Float(), nullable=True),
    sa.Column('max_ideal', sa.Float(), nullable=True),
    sa.Column('invert', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpis_key'), 'kpis', ['key'], unique=True)
    op.create_table('kpi_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('kpi_id', sa.String(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('normalized_0_100', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_values')
    op.drop_index(op.f('ix_kpis_key'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pillars_key'), table_name='pillars')
    op.drop_table('pillars')
    # ### end Alembic commands ###
