"""add project_pillar_scores table

Revision ID: 93714713f947
Revises: 54a4d5959155
Create Date: 2025-11-12 13:58:00.221706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93714713f947'
down_revision: Union[str, Sequence[str], None] = '54a4d5959155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_pillar_scores',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('pillar_key', sa.Text(), nullable=False),
    sa.Column('raw_score_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('final_score_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id', 'pillar_key'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_pillar_scores', schema='public')
    # ### end Alembic commands ###
