"""sync to db schema truth

Revision ID: dc53c49f38cb
Revises: 9f1b2c3d4e5f
Create Date: 2026-01-26 19:39:41.319946
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dc53c49f38cb"
down_revision: Union[str, Sequence[str], None] = "9f1b2c3d4e5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerated while ORM metadata didn’t match live DB; keep as no-op to avoid drops/alterations.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass